# Generated by Django 3.2.6 on 2021-09-29 20:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20210929_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 29, 20, 34, 54, 557191, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='image',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 29, 20, 34, 54, 557833, tzinfo=utc)),
        ),
    ]
