# Generated by Django 3.2.6 on 2021-10-04 20:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import gallery.models
import gallery.validators


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20210929_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 4, 20, 0, 23, 689046, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='image',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 4, 20, 0, 23, 689801, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=gallery.models.upload_gallery_image, validators=[gallery.validators.validate_image_file_extension]),
        ),
    ]
